# Disabled - Mayhem workflow only
name: golangci-lint
on:
  push:
    branches: [ "disabled-by-mayhem-setup" ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - run: echo "disabled"
