# Disabled - Mayhem workflow only
name: amqp091-go
on:
  push:
    branches: [ "disabled-by-mayhem-setup" ]
jobs:
  build:
    name: disabled
    runs-on: ubuntu-latest
    steps:
    - run: echo "disabled"
